# Generated by Django 4.1.3 on 2022-11-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data_type',
            field=models.CharField(default=2021, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='detection_model',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
